### ISSUE TITLE
Staging Kicks Player Out Of PCR

### ISSUE THREAD

**Issue by GoldwingDesigns** [JonnyOThan/KSP-ProbeControlRoom#21]
When in PCR staging (after the initial stage) causes the player to get kicked out of Probe Control Room.  Log at this link: https://oshi.at/AeLA/KSPBugReport_2023-03-04_133654.zip

-Orionguy

**Comment by JonnyOThan** [comment]
Dupe of #14

**Comment by GoldwingDesigns** [comment]
Sorry Jonny, I did look, but I must have missed the dupe before submitting
the issue.  Thanks again for all your hard work!!

All the best,

Orionguy
Matt Perry

**Comment by JonnyOThan** [comment]
No worries, I even opened a dupe myself: https://github.com/JonnyOThan/KSP-ProbeControlRoom/issues/16
