### ISSUE TITLE
Cannot exit seat

### ISSUE THREAD

**Issue by Kam1ni** [JonnyOThan/KSP-ProbeControlRoom#23]
When trying to exit seat with FreeIVA nothing will happen and you get the message cannot unbuckle in this part.

[KSP.log](https://github.com/JonnyOThan/KSP-ProbeControlRoom/files/10959811/KSP.log)

**To reproduce**
1. Create a vessel with a probe core (I tested with stayputnik and QBE)
2. Enter pcr
3. Try to exit seat with freeIVA by pressing Y or using the buckle in VR

I was hoping I could exit the seat now and climb the wall in VR to finally change what's displayed on the big screens.

 - OS: Windows 10
 - KSP Version: 1.12.5
 - VR Hardware: Vive with Knuckles controllers
 - Kerbal-VR Version: 0.9.2.0
 - PCR Version: 1.3.2.0
 - FreeIVA Version: 0.2.10.3

**Comment by JonnyOThan** [comment]
I believe this was fixed in https://github.com/pizzaoverhead/FreeIva/commit/858364ab74881c0baf25171cedf6fcc02e2d24a3
